//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inspeccion
    {
        public int Id { get; set; }
        public Nullable<int> Idvehiculo { get; set; }
        public Nullable<int> Idcliente { get; set; }
        public string TieneRalladuras { get; set; }
        public string CantidadCombustible { get; set; }
        public string TieneGomaRepuesta { get; set; }
        public string TieneGato { get; set; }
        public string TieneRoturasCristal { get; set; }
        public string EstadoGomas { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> IdEmpleadoInspeccion { get; set; }
        public string Estado { get; set; }
    }
}
