//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3
{
    using System;
    using System.Collections.Generic;
    
    public partial class RentaDevolucion
    {
        public int NoRenta { get; set; }
        public int Idempleado { get; set; }
        public int Idvehiculo { get; set; }
        public int IdCliente { get; set; }
        public System.DateTime FechaRenta { get; set; }
        public System.DateTime FechaDevolucion { get; set; }
        public Nullable<long> Montoxdia { get; set; }
        public Nullable<int> CantidadDeDias { get; set; }
        public string Comentario { get; set; }
        public string Estado { get; set; }
    }
}
