//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehiculo
    {
        public int Id { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> NChasis { get; set; }
        public Nullable<int> NMotor { get; set; }
        public string NPlaca { get; set; }
        public string TipoDeVehiculo { get; set; }
        public string Marca { get; set; }
        public string Modelo { get; set; }
        public string TipoDeCombustible { get; set; }
        public string Estado { get; set; }
    }
}
